### ISSUE TITLE
Message handler doesn't receive messages

### ISSUE THREAD

**Issue by jhoogstraat** [rikulo/socket.io-client-dart#167] opened 2021-03-18 15:00 UTC
Since 2.0.0-beta.3-nullsafety.0 my message handler don't receive message anymore.
The logger is showing all messages fine, but the callbacks are not firing.

**Comment by Curvel** [comment] 2021-03-22 19:00
I got the same issue

**Comment by sha-N** [comment] 2021-03-25 14:08
@jhoogstraat @Curvel are you trying to transfer binary data. For me problem is when I try to transfer binary data. 2.0.0-beta.1 handles binary data without any issue.

**Comment by Curvel** [comment] 2021-03-25 14:27
@sha-N Exactly, I try to receive a byte stream.

**Comment by sha-N** [comment] 2021-03-25 15:45
my workaround was to base64encode at server side and decode at client side
in nodejs server
`data: data.toString('base64'),`

in dart client
`final List<int> _data = base64Decode(data);`

**Comment by jumperchen** [comment] 2021-03-26 02:27
@sha-N @jhoogstraat  Does any full example to demonstrate this issue? Because I cannot reproduce it on my local env. with `2.0.0-beta.3-nullsafety.0`

**Comment by sha-N** [comment] 2021-03-27 06:47
@jumperchen first of all great work on the library.

To reproduce the issue, try to send any Buffer data from nodejs socketio server to dart client. like gzip data from server.

```
zlib = require('zlib');
zlib.gzip(data, (err, zipped) => { 
    io.to('client-id').emit('event-name', {id: 'some-id', data: zipped});
});
```

Sending buffer data from dart client to nodejs server works perfectly.

**Comment by jumperchen** [comment] 2021-03-29 04:31
Fixed by running `pub upgrade` for `socket_io_common`

**Closed by jumperchen** 2021-03-29 04:31 UTC
Labels: bug
