### ISSUE TITLE
socket id's not synced

### ISSUE THREAD

**Issue by arbaker2** [rikulo/socket.io-client-dart#172] opened 2021-03-27 20:27 UTC
When using 2.0.0-beta.3-nullsafety.0 I am seeing different values for socket.id on the client and the server when I initiate a connection. However when I revert back to V0.9.12 I the values appear the same as they should be. Am I the only one experiencing this issue? For reference I am using socket.io V4.0.0 on the server side.

**Comment by k3vinb0ss** [comment] 2021-04-05 07:41
Having the same issue. please fix

**Comment by jumperchen** [comment] 2021-04-28 03:45
Fixed in `2.0.0-beta.4-nullsafety.0`, please to give it a try if the problem is fixed.

**Closed by jumperchen** 2021-04-28 03:45 UTC

**Comment by arbaker2** [comment] 2021-04-28 20:06
socket id's are now matching for me. Thanks for the fix. Also, I am using socket.io v3 on the server side.
